version: "3.9"

services:
  qa-ui:
    image: ghcr.io/olli-suoniemi/qa-project/qa-ui:latest
    depends_on:
      - qa-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qa-ui.rule=Host(`qa.olli.codes`)"
      - "traefik.http.routers.qa-ui.entrypoints=websecure"
      - "traefik.http.routers.qa-ui.tls.certresolver=myresolver"
      - "traefik.http.services.qa-ui.loadbalancer.server.port=3000"

      # Define HSTS middleware
      - "traefik.http.middlewares.hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"

      # Attach HSTS middleware to this router
      - "traefik.http.routers.qa-ui.middlewares=hsts"
    networks:
      - internal
      - proxy
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s

  qa-api:
    image: ghcr.io/olli-suoniemi/qa-project/qa-api:latest
    depends_on:
      - database
      - flyway
      - redis
    environment:
      PGUSER_FILE: /run/secrets/PGUSER
      PGPASSWORD_FILE: /run/secrets/PGPASSWORD
      PGDATABASE_FILE: /run/secrets/PGDATABASE
      PGHOST_FILE: /run/secrets/PGHOST
      PGPORT_FILE: /run/secrets/PGPORT
    secrets:
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGHOST
      - PGPORT
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qa-api.rule=Host(`qa.olli.codes`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.qa-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.qa-api.middlewares=qa-api-stripprefix"
      - "traefik.http.routers.qa-api.entrypoints=websecure"
      - "traefik.http.routers.qa-api.tls.certresolver=myresolver"
      - "traefik.http.services.qa-api.loadbalancer.server.port=7777"
    networks:
      - internal
      - proxy
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s

  llm-api:
    image: ghcr.io/olli-suoniemi/qa-project/llm-api:latest
    depends_on:
      - database
      - flyway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-api.rule=Host(`qa.olli.codes`) && PathPrefix(`/llm`)"
      - "traefik.http.middlewares.llm-api-stripprefix.stripprefix.prefixes=/llm"
      - "traefik.http.routers.llm-api.middlewares=llm-api-stripprefix"
      - "traefik.http.routers.llm-api.entrypoints=websecure"
      - "traefik.http.routers.llm-api.tls.certresolver=myresolver"
      - "traefik.http.services.llm-api.loadbalancer.server.port=7000"
    environment:
      OPENAI_API_KEY_FILE: /run/secrets/OPENAI_API_KEY
    secrets:
      - OPENAI_API_KEY
    networks:
      - internal
      - proxy
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s

  websocket:
    image: ghcr.io/olli-suoniemi/qa-project/websocket:latest
    depends_on:
      - redis
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qa-websocket.rule=Host(`qa.olli.codes`) && PathPrefix(`/ws`)"
      - "traefik.http.middlewares.qa-ws-stripprefix.stripprefix.prefixes=/ws"
      - "traefik.http.routers.qa-websocket.middlewares=qa-ws-stripprefix"
      - "traefik.http.services.qa-websocket.loadbalancer.server.port=7788"
      - "traefik.http.routers.qa-websocket.entrypoints=websecure"
      - "traefik.http.routers.qa-websocket.tls.certresolver=myresolver"
        
  redis:
    image: redis:latest
    command: >
      redis-server --maxmemory 500mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    networks:
      - internal

  database:
    image: postgres:16.1
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGUSER
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      PGUSER_FILE: /run/secrets/PGUSER
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d `cat $$POSTGRES_DB_FILE` -U `cat $$PGUSER_FILE`" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  flyway:
    image: ghcr.io/olli-suoniemi/qa-project/flyway:latest
    depends_on:
      - database
    environment:
      FLYWAY_USER_FILE: /run/secrets/FLYWAY_USER
      FLYWAY_PASSWORD_FILE: /run/secrets/FLYWAY_PASSWORD
      FLYWAY_URL_FILE: /run/secrets/FLYWAY_URL
    secrets:
      - FLYWAY_USER
      - FLYWAY_PASSWORD
      - FLYWAY_URL
    networks:
      - internal
    deploy:
      restart_policy:
        condition: none 

volumes:
  astro_node_modules:
  db-data:
  letsencrypt:
  flyway-sql:
    driver: local 

secrets:
  PGUSER:
    external: true
  PGPASSWORD:
    external: true
  PGDATABASE:
    external: true
  PGHOST:
    external: true
  PGPORT:
    external: true
  DATABASE_URL:
    external: true

  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_DB:
    external: true

  FLYWAY_USER:
    external: true
  FLYWAY_PASSWORD:
    external: true
  FLYWAY_URL:
    external: true 

  OPENAI_API_KEY:
    external: true 

networks:
  proxy:
    external: true
  internal:
    driver: overlay