apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
  namespace: production
spec:
  template:
    metadata:
      name: database-migration-job
    spec:
      containers:
        - name: database-migrations
          image: ghcr.io/olli-suoniemi/qa-project/flyway:latest
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: database-cluster-app
                  key: username
                  optional: false
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-cluster-app
                  key: password
                  optional: false
            - name: DATABASE_CLUSTER_RW_SERVICE_HOST
              value: "database-cluster-rw.production.svc.cluster.local"
            - name: DATABASE_CLUSTER_RW_SERVICE_PORT
              value: "5432"
      restartPolicy: Never
  backoffLimit: 2