apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
  namespace: production
spec:
  instances: 1

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: "500m"   # Request half a CPU core
      memory: 1Gi   # Request 1GB of RAM
    limits:
      cpu: "1"      # Limit to 1 CPU core per pod
      memory: 2Gi   # Limit to 2GB of RAM per pod